export const navLinks=[
    {
        id:'home',
        title:'Home',
    },
    {
        id:'portfolio',
        title:'PORTFOLIO',
    },
    {
        id:'Blog',
        title:'BLOG',
    },
    {
        id:'team',
        title:'TEAM',
    },
    {
        id:'services',
        title:'Services',
    },
    {
        id:'reviews',
        title:'REVIEWS',
    },
    {
        id:'aboutus',
        title:'ABOUTUS',
    },
    {
        id:'contacts',
        title:'CONTACTS',
    },
]